baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Desque'

#main nav menu
[[ menu.main ]]
name = "Home"
url = "/"
weight = 1

[[ menu.main ]]
name = "About"
url = "/about"
weight = 2

[[ menu.main ]]
name = "Services"
url = "/services"
weight = 3

[[ menu.main ]]
name = "Portfolio"
url = "/portfolio"
weight = 4

[[ menu.main ]]
name = "Contact"
url = "/contact"
weight = 5

#footer
[[ menu.footer ]]
name = "Terms"
url = "/terms"
weight = 1

[[ menu.footer ]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2

[[ menu.footer ]]
name = "FAQ"
url = "/privacy-policy"
weight = 3
